version: '3'
services:

  postgres:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - "panchan-postgres-data:/data/postgres"
    restart: always
    env_file:
      - .docker.env

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "5555:5555"
    env_file:
      - .docker.env
    restart: always
    links:
      - "postgres:database"

volumes:
  panchan-postgres-data:
